services:
  server:
    image: orojas12/simpleweather-server:1.0
    container_name: simpleweather-server
  nginx:
    image: orojas12/simpleweather-nginx:1.0.1
    container_name: simpleweather-nginx
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
    ports:
      - "443:443"
    depends_on:
      - server
