services:
  server:
    build: ./server
    container_name: simpleweather_server
  nginx:
    build: ./client
    container_name: simpleweather_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - server
